[package]
name = "graft"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "2.33.3"
diffy = "0.2.0"
flate2 = "1.0.17"
reqwest = { version = "0.10.7", features = ["blocking"] }
serde = { version = "1.0.111", features = ["derive"] }
serde_json = "1.0.55"
tar = "0.4.29"
url = "2.1.1"